[".config/bat/themes/catppuccin-mocha.tmTheme"]
type = 'file'
url = 'https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme'
refreshPeriod = "168h"

[".config/fish/themes/catppuccin_mocha.theme"]
type = 'file'
url = 'https://raw.githubusercontent.com/catppuccin/fish/refs/heads/main/themes/Catppuccin%20Mocha.theme'
refreshPeriod = "168h"

[".config/nushell/autoload/catppuccin_mocha.nu"]
type = 'file'
url = 'https://raw.githubusercontent.com/catppuccin/nushell/refs/heads/main/themes/catppuccin_mocha.nu'
refreshPeriod = "168h"

[".config/zellij/plugins/zjstatus.wasm"]
type = 'file'
url = 'https://github.com/dj95/zjstatus/releases/latest/download/zjstatus.wasm'
refreshPeriod = "168h"

[".config/zellij/plugins/vim-zellij-navigator.wasm"]
type = 'file'
url = 'https://github.com/hiasr/vim-zellij-navigator/releases/latest/download/vim-zellij-navigator.wasm'
refreshPeriod = "168h"
