#!/usr/bin/env zsh

local -i color

print -P -- '%F{white}System colours:'
for (( color=0; color < 16; color++ )) {
  (( color / 8.0 == 1 )) && print
  print -nP -- "%F{$color}${(l.4.. .)color}"
}
print

print -P -- '%F{white}Grayscale ramp:'
for (( color=232; color < 256; color++ ))
  print -nP -- "%F{$color}${(l.4.. .)color}"
print

print -P -- '%F{white}Colour cube, 6x6x6:'
for (( green=0; green < 6; green++ )) {
  for (( red=0; red < 6; red++ )) {
    for (( blue=0; blue < 6; blue++ )) {
      (( color = 16 + (red * 36)  + (green  * 6) + blue ))
      print -nP -- "%F{$color}${(l.4.. .)color}"
    }
  }
  print
}
